name: Build and Publish Ubuntu Runner

on:
  push:
    branches:
    - master
    paths:
      - 'runner/ubuntu/**'    
  workflow_dispatch:
  workflow_call:

jobs:
  build-ubuntu-latest:
    uses: ./.github/workflows/_update_image.yml
    with:
      buildFile: "runner/ubuntu/Latest"
      tag: "dahool/ubuntu-runner:act-latest"
    secrets: inherit    
