# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and Publish JDK 22

on:
  push:
    branches:
    - master
    paths:
      - 'maven/jdk22/**'    
  workflow_dispatch:
  workflow_call:

jobs:
  build-jdk21-node18:
    uses: ./.github/workflows/_update_image.yml
    with:
      buildFile: "maven/jdk22/Node18"
      tag: "dahool/maven-node:maven3-openjdk-22-node18"
    secrets: inherit    
  build-jdk21-node20:
    uses: ./.github/workflows/_update_image.yml
    with:
      buildFile: "maven/jdk22/Node20"
      tag: "dahool/maven-node:maven3-openjdk-22-node20"
    secrets: inherit
  build-jdk21-node22:
    uses: ./.github/workflows/_update_image.yml
    with:
      buildFile: "maven/jdk22/Node22"
      tag: "dahool/maven-node:maven3-openjdk-22-node22"
    secrets: inherit    