# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and Publish

on:
  push:
    branches:
    - master
  workflow_dispatch:

jobs:
  build-jdk11-node18:
      uses: ./.github/workflows/_update_image.yml
      with:
        buildFile: "maven/jdk11/Node18"
        tag: "dahool/maven-node:maven3-openjdk-11-nodelts,dahool/maven-node:maven3-openjdk-11-node18"
      secrets: inherit
  build-jdk11-node16:
    uses: ./.github/workflows/_update_image.yml
    with:
      buildFile: "maven/jdk11/Node16"
      tag: "dahool/maven-node:maven3-openjdk-11-node16"
    secrets: inherit
  build-jdk20-node18:
    uses: ./.github/workflows/_update_image.yml
    with:
      buildFile: "maven/jdk20/Node18"
      tag: "dahool/maven-node:maven3-openjdk-20-nodelts,dahool/maven-node:maven3-openjdk-20-node18"
    secrets: inherit    
  build-jdk20-node20:
    uses: ./.github/workflows/_update_image.yml
    with:
      buildFile: "maven/jdk20/Node20"
      tag: "dahool/maven-node:maven3-openjdk-20-node20"
    secrets: inherit